server:
  port: 8080

spring:

  application:
    name: main-app


  datasource:
    url: jdbc:postgresql://localhost:5432/platform_db?currentSchema=main
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: main
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: main
    default-schema: main

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

  graphql:
    schema:
      locations: classpath:graphql/**/
      file-extensions: .graphqls,.gqls
    graphiql:
      enabled: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000        # 24 hours
    refresh-expiration-ms: 604800000  # 7 days